### PR TITLE
Upgrade openssl-1.0.1m

### PR DESCRIPTION
**Pull request by deepj**

### CODE REVIEW

**Comment by mislav** [comment]
Thanks!

OpenSSL 1.0.1 is halfway through the alphabet already. When they get to the end, I wonder if they'll consider using numbers for versioning again.

**Comment by deepj** [comment]
Nope, they stop at `z` and they start from the beginning on the second position :smile: i.e. `openssl-0.9.8zf.tar.gz` 

https://www.openssl.org/source/

It'd be nice to consider to release new ruby-build when new openssl was released. But that's up to you.

**Comment by sferik** [comment]
Yeah, I’ll make a release. I think this is the only change since the last release, so the release notes should be easy.

**Comment by mislav** [comment]
@sferik: ruby-build 20150319zf

**Comment by deepj** [comment]
:smile_cat:

**Comment by sferik** [comment]
@mislav I am so doing that.

**Comment by mislav** [comment]
Oh wow he actually did it :joy_cat:

**Pull request merged**
