### PR TITLE
add ruby 2.0.0-p645

### PR DESCRIPTION
**Pull request by DomT4**

### CODE REVIEW

**Comment by DomT4** [comment]
Oops. Pushed the wrong file, that was stupid. One sec.

**Comment by philsturgeon** [comment]
I fixed the original chaps PR here https://github.com/sstephenson/ruby-build/pull/741

**Comment by beedub** [comment]
closing in favor of https://github.com/sstephenson/ruby-build/pull/741

**Comment by DomT4** [comment]
It closed magically anyway :wink:

**Pull request closed without merging**
